### ISSUE TITLE
Unknown license

### ISSUE THREAD

**Issue by mazegen** [Plaban9/Game_Space_Invader#1]
Thank you for the source code, I appreciate it. Can you please specify license?

**Comment by Plaban9** [comment]
Hello,
I have very little knowledge about licensing and therefore, I am going for most widely used license (GPLv3). In case of any further suggestion or query, you can contact me.

P.S.: The game is hosted for a limited period of time at https://www.gamebucket.io/game/cc10f233-3265-440b-a8fa-750ac0964680. You can also try the game and some suggestions will be much appreciated.

**Comment by mazegen** [comment]
If you want others to contribute back to your repository, GPL is good choice. If you don't insist on contributing back, please choose another license because GPL is very restrictive and would discurage many people.

**Comment by Plaban9** [comment]
So, should I go for Apache 2 or MIT?. I am preferring Apache 2 because it contains the State Change documentation condition.

**Comment by Plaban9** [comment]
I have chosen the Apache License 2.0, Thanks for the information.
